### ISSUE TITLE
Contribute to Java and JavaScript Exercises

### ISSUE THREAD

**Issue by HighnessAtharva** [HighnessAtharva/W3Resource-Python#3]
## Completing JavaScript and Java Exercises

Create a Folder titled `Collections` in the `Java` Directory and fill in solutions accordingly. 
If interested, please reply to this issue. **Templates will be created under 24 hours so you can proceed with adding solutions**. 

- [ ] Javascript --> All Exercises pending. 
- [ ] Java --> Collections Directory Exercises Pending. **PRIORITY**

**Comment by nukala-surender** [comment]
I can work on java String solutions. Let me know the steps

**Comment by HighnessAtharva** [comment]
> I can work on java String solutions. Let me know the steps

Thank you for your interest. 
Please visit https://www.w3resource.com/java-exercises/string/index.php and copy each of the solutions from the question to the `string.java` file in the `Java` directory. 
There is a blank template ready for your convenience. Send a PR after you're done and I'll merge it.
